site_name: skateboard
site_url: https://phasewalk1.github.io/skateboard
repo_url: https://github.com/phasewalk1/skateboard
site_author: skateboard Developers
docs_dir: dist

nav:
  - index.md
  - Options:
    - ./cobra/skateboard.md 
    - install: ./cobra/skateboard_install.md
    - new: ./cobra/skateboard_new.md
    - check: ./cobra/skateboard_check.md
    - sync: ./cobra/skateboard_sync.md
    - up: ./cobra/skateboard_up.md
    - service: ./cobra/skateboard_service.md
    - mkdocs: ./cobra/skateboard_mkdocs.md
    - completion: ./cobra/skateboard_completion.md 
  - Trucks:
    - sections/trucks/index.md

theme:
  name: material
  palette:
    scheme: slate
  logo: ./assets/skateboard.svg
  favicon: ./assets/skateboard.svg
  highlightjs: true
  hljs_languages:
    - yaml
  features:
    - toc.integrate
    - toc.follow
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - content.code.copy

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences



